MODULE := engines/legend

MODULE_OBJS = \
	gfx/compass.o \
	gfx/font.o \
	gfx/image.o \
	gfx/mouse_cursor.o \
	gfx/picture.o \
	gfx/region.o \
	gfx/screen.o \
	gfx/view_element.o \
	gfx/view.o \
	utils/engine_data.o \
	utils/file.o \
	utils/resources.o \
	utils/string.o \
	early/engine.o \
	early/core/persisted.o \
	early/gfx/boxed_element.o \
	early/gfx/button.o \
	early/gfx/command_buttons.o \
	early/gfx/input_window.o \
	early/gfx/listbox.o \
	early/gfx/scene.o \
	early/gfx/screen.o \
	early/gfx/text_window.o \
	early/gfx/view.o \
	early/logic/logic_base.o \
	early/logic/logics.o \
	early/logic/room.o \
	early/logic/queue.o \
	early/parser/parser.o \
	early/parser/parser_handlers.o \
	early/parser/vocab.o \
	early/parser/vocab_set.o \
	early/utils/huffman.o \
	early/views/help_screen.o \
	early/views/interface.o \
	games/gateway/engine.o \
	games/gateway/core/persisted.o \
	games/gateway/logic/logics.o \
	games/gateway/logic/logic_strings.o \
	games/gateway/logic/rooms/room001.o \
	games/gateway/logic/rooms/room002.o \
	games/gateway/logic/rooms/room003.o \
	games/gateway/logic/rooms/room004.o \
	games/gateway/logic/rooms/room005.o \
	games/gateway/logic/rooms/room006.o \
	games/gateway/logic/rooms/room007.o \
	games/gateway/logic/rooms/room008.o \
	games/gateway/logic/rooms/room009.o \
	games/gateway/logic/rooms/room010.o \
	games/gateway/logic/rooms/room018.o \
	games/gateway/logic/rooms/room019.o \
	games/gateway/logic/rooms/room033.o \
	games/gateway/logic/rooms/room034.o \
	games/gateway/logic/rooms/room035.o \
	games/gateway/logic/rooms/room036.o \
	games/gateway/logic/rooms/room070.o \
	games/gateway/logic/rooms/room071.o \
	games/gateway/logic/rooms/room072.o \
	games/gateway/logic/rooms/room073.o \
	games/gateway/logic/rooms/room074.o \
	games/gateway/logic/rooms/room075.o \
	games/gateway/logic/rooms/room141.o \
	games/gateway/logic/rooms/room142.o \
	games/gateway/logic/rooms/room143.o \
	games/gateway/logic/rooms/room144.o \
	games/gateway/logic/rooms/room145.o \
	games/gateway/logic/rooms/room146.o \
	games/gateway/logic/rooms/room147.o \
	games/gateway/logic/rooms/room148.o \
	games/gateway/logic/rooms/room149.o \
	games/gateway/logic/rooms/room150.o \
	games/gateway/logic/rooms/room151.o \
	games/gateway/logic/rooms/room152.o \
	games/gateway/logic/rooms/room153.o \
	games/gateway/logic/rooms/room154.o \
	games/gateway/logic/rooms/room155.o \
	games/gateway/logic/rooms/room156.o \
	games/gateway/logic/rooms/room231.o \
	games/gateway/logic/rooms/room232.o \
	games/gateway/logic/rooms/room233.o \
	games/gateway/logic/rooms/room234.o \
	games/gateway/logic/rooms/room235.o \
	games/gateway/logic/rooms/room236.o \
	games/gateway/logic/rooms/room237.o \
	games/gateway/logic/rooms/room238.o \
	games/gateway/logic/rooms/room239.o \
	games/gateway/logic/rooms/room240.o \
	games/gateway/logic/rooms/room241.o \
	games/gateway/logic/rooms/room242.o \
	games/gateway/logic/rooms/room243.o \
	games/gateway/logic/rooms/room244.o \
	games/gateway/logic/rooms/room245.o \
	games/gateway/logic/rooms/room246.o \
	games/gateway/logic/rooms/room247.o \
	games/gateway/logic/rooms/room248.o \
	games/gateway/logic/rooms/room249.o \
	games/gateway/logic/rooms/room250.o \
	games/gateway/logic/rooms/room251.o \
	games/gateway/logic/rooms/room252.o \
	games/gateway/logic/rooms/room253.o \
	games/gateway/logic/rooms/room254.o \
	games/gateway/logic/rooms/room433.o \
	games/gateway/logic/rooms/room442.o \
	games/gateway/logic/rooms/room443.o \
	games/gateway/logic/rooms/room444.o \
	games/gateway/logic/rooms/room445.o \
	games/gateway/logic/rooms/room446.o \
	games/gateway/logic/rooms/room447.o \
	games/gateway/logic/rooms/room448.o \
	games/gateway/logic/rooms/room449.o \
	games/gateway/logic/rooms/room450.o \
	games/gateway/logic/rooms/room451.o \
	games/gateway/logic/rooms/room452.o \
	games/gateway/logic/rooms/room453.o \
	games/gateway/logic/rooms/room454.o \
	games/gateway/logic/rooms/room455.o \
	games/gateway/logic/rooms/room456.o \
	games/gateway/logic/rooms/room457.o \
	games/gateway/logic/rooms/room458.o \
	games/gateway/logic/rooms/room560.o \
	games/gateway/logic/rooms/room561.o \
	games/gateway/logic/rooms/room562.o \
	games/gateway/logic/rooms/room563.o \
	games/gateway/logic/rooms/room564.o \
	games/gateway/logic/rooms/room595.o \
	games/gateway/logic/rooms/room596.o \
	games/gateway/logic/rooms/room597.o \
	games/gateway/logic/rooms/room598.o \
	games/gateway/logic/rooms/room599.o \
	games/gateway/logic/rooms/room600.o \
	games/gateway/logic/rooms/room621.o \
	games/gateway/logic/rooms/room622.o \
	games/gateway/logic/rooms/room623.o \
	games/gateway/logic/rooms/room624.o \
	games/gateway/logic/rooms/room625.o \
	games/gateway/logic/rooms/room626.o \
	games/gateway/logic/rooms/room627.o \
	games/gateway/logic/rooms/room628.o \
	games/gateway/logic/rooms/room629.o \
	games/gateway/logic/rooms/room630.o \
	games/gateway/logic/rooms/room656.o \
	games/gateway/logic/rooms/room666.o \
	games/gateway/logic/rooms/room667.o \
	games/gateway/logic/rooms/room686.o \
	games/gateway/logic/rooms/room700.o \
	games/gateway/logic/rooms/room715.o \
	games/gateway/logic/rooms/room717.o \
	games/gateway/parser/parser.o \
	games/gateway/parser/vocab.o \
	games/gateway/views/commset.o \
	games/gateway/views/part_title.o \
	legend.o \
	console.o \
	events.o \
	messages.o \
	metaengine.o

# This module can be built as a plugin
ifeq ($(ENABLE_LEGEND), DYNAMIC_PLUGIN)
PLUGIN := 1
endif

# Include common rules
include $(srcdir)/rules.mk

# Detection objects
DETECT_OBJS += $(MODULE)/detection.o
